"""Apply dark theme to all QLDPC simulation modules and regenerate every plot.

Usage
-----
    python generate_all_plots.py                     # PNGs + GIFs
    python generate_all_plots.py --skip-animations   # PNGs only (much faster)

What it does
------------
1. Reads each simulation module under ``qldpc/simulation/``.
2. Injects dark-theme rcParams and rewrites hard-coded light-theme colors.
3. Writes the modified files back (idempotent — safe to re-run).
4. Imports each module and calls its ``main()`` to regenerate every figure
   into the ``Plots/`` directory.
"""

from __future__ import annotations

import importlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SIM_DIR = os.path.join(ROOT, "qldpc", "simulation")

# ── Dark-theme rcParams block (injected into every module) ────────────────
DARK_RCPARAMS_BLOCK = """
# --- Dark Theme Configuration (auto-generated by generate_all_plots.py) ---
import matplotlib as _mpl
_mpl.rcParams.update({
    "figure.facecolor":  "#1a1a1a",
    "axes.facecolor":    "#111111",
    "savefig.facecolor": "#1a1a1a",
    "savefig.edgecolor": "none",
    "text.color":        "#ffffff",
    "axes.labelcolor":   "#ffffff",
    "xtick.color":       "#ffffff",
    "ytick.color":       "#ffffff",
    "axes.edgecolor":    "#444444",
    "axes.titlecolor":   "#ffffff",
    "grid.color":        "#2d2d2d",
    "legend.facecolor":  "#1e1e1e",
    "legend.edgecolor":  "#444444",
    "legend.labelcolor": "#ffffff",
    "figure.edgecolor":  "#1a1a1a",
})
# --- End Dark Theme ---
"""

# ── Simple string replacements ────────────────────────────────────────────
_SIMPLE: list[tuple[str, str]] = [
    # Redefine lightCmap so every lightCmap(x) produces a dark-friendly color
    (
        "lightCmap = sns.cubehelix_palette(start=2, rot=0, dark=0, light=.95, "
        "reverse=True, as_cmap=True)",
        "lightCmap = sns.cubehelix_palette(start=2, rot=0, dark=0.05, light=0.45, "
        "reverse=True, as_cmap=True)",
    ),
    # Text-box / patch backgrounds
    ("facecolor='white'", "facecolor='#1e1e1e'"),
    ("facecolor='lightgreen'", "facecolor='#0a3a1a'"),
    # Structural edges & markers that were black → light gray
    ("edgecolor='black'", "edgecolor='#aaaaaa'"),
    ("color='black'", "color='#cccccc'"),
    # Named colours that are too dark on #111 background
    ("color='blue'", "color='#5dade2'"),
    ("color='green'", "color='#00cc66'"),
    ("color='darkgreen'", "color='#00aa44'"),
    ("color='gray'", "color='#999999'"),
    ("facecolor='gray'", "facecolor='#555555'"),
    ("color='orange'", "color='#ff9f43'"),
]

# ── Regex replacements for matplotlib format-string colours ───────────────
_REGEX: list[tuple[str, str]] = [
    # 'k-' (black solid)
    (r",\s*'k-'\s*,", ", color='#cccccc',"),
    (r",\s*'k-'\s*\)", ", color='#cccccc')"),
    # 'k:' (black dotted)
    (r",\s*'k:'\s*,", ", color='#888888', linestyle=':',"),
    (r",\s*'k:'\s*\)", ", color='#888888', linestyle=':')" ),
    # 'k--' (black dashed)
    (r",\s*'k--'\s*,", ", color='#888888', linestyle='--',"),
    (r",\s*'k--'\s*\)", ", color='#888888', linestyle='--')"),
    # 'r-' → brighter red
    (r",\s*'r-'\s*,", ", color='#ff6b6b',"),
    (r",\s*'r-'\s*\)", ", color='#ff6b6b')"),
    # 'g-' → brighter green
    (r",\s*'g-'\s*,", ", color='#00cc66',"),
    (r",\s*'g-'\s*\)", ", color='#00cc66')"),
    # 'b-' → brighter blue
    (r",\s*'b-'\s*,", ", color='#5dade2',"),
    (r",\s*'b-'\s*\)", ", color='#5dade2')"),
]


def apply_dark_theme_to_module(filepath: str) -> None:
    """Read *filepath*, inject dark-theme colours, write back."""
    with open(filepath, "r", encoding="utf-8") as fh:
        code = fh.read()

    if "# --- Dark Theme Configuration" in code:
        print(f"  [skip] {os.path.basename(filepath)} (already themed)")
        return

    # 1. Insert the rcParams block before the first function definition
    match = re.search(r"\ndef ", code)
    if match:
        pos = match.start()
        code = code[:pos] + DARK_RCPARAMS_BLOCK + code[pos:]

    # 2. Simple string replacements
    for old, new in _SIMPLE:
        code = code.replace(old, new)

    # 3. Regex replacements (format-string colours)
    for pattern, repl in _REGEX:
        code = re.sub(pattern, repl, code)

    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(code)

    print(f"  [done] {os.path.basename(filepath)}")


def main() -> None:
    print("=" * 60)
    print("QLDPC — Dark-Theme Plot Generator")
    print("=" * 60)

    # ── 1. Patch source modules ──────────────────────────────────────────
    print("\n1  Applying dark theme to simulation modules …")
    module_names = [
        "cavity_gates.py",
        "ghz.py",
        "syndrome.py",
        "quantum_circuits.py",
        "animations.py",
    ]
    for name in module_names:
        path = os.path.join(SIM_DIR, name)
        if os.path.exists(path):
            apply_dark_theme_to_module(path)
        else:
            print(f"  [warn] {name} not found")

    # ── 2. Ensure Plots/ exists ──────────────────────────────────────────
    plots_dir = os.path.join(ROOT, "Plots")
    os.makedirs(plots_dir, exist_ok=True)

    # ── 3. Global rcParams (covers anything the module-level block misses)
    import matplotlib as mpl

    mpl.rcParams.update(
        {
            "figure.facecolor": "#1a1a1a",
            "axes.facecolor": "#111111",
            "savefig.facecolor": "#1a1a1a",
            "savefig.edgecolor": "none",
            "text.color": "#ffffff",
            "axes.labelcolor": "#ffffff",
            "xtick.color": "#ffffff",
            "ytick.color": "#ffffff",
            "axes.edgecolor": "#444444",
            "axes.titlecolor": "#ffffff",
            "grid.color": "#2d2d2d",
            "legend.facecolor": "#1e1e1e",
            "legend.edgecolor": "#444444",
            "legend.labelcolor": "#ffffff",
            "figure.edgecolor": "#1a1a1a",
        }
    )

    # ── 4. Generate static PNGs ──────────────────────────────────────────
    sys.path.insert(0, ROOT)

    print("\n2  Generating static plots (PNGs) …")
    for mod_dotpath in [
        "qldpc.simulation.cavity_gates",
        "qldpc.simulation.ghz",
        "qldpc.simulation.syndrome",
        "qldpc.simulation.quantum_circuits",
    ]:
        mod = importlib.import_module(mod_dotpath)
        importlib.reload(mod)
        mod.main()

    # ── 5. Optionally generate GIF animations ────────────────────────────
    skip_anims = "--skip-animations" in sys.argv
    if skip_anims:
        print("\n3  Skipping GIF animations (--skip-animations)")
    else:
        print("\n3  Generating GIF animations (this may take several minutes) …")
        mod = importlib.import_module("qldpc.simulation.animations")
        importlib.reload(mod)
        mod.main()

    print("\n" + "=" * 60)
    print("All dark-themed plots generated in Plots/")
    print("=" * 60)


if __name__ == "__main__":
    main()
